### ISSUE TITLE
Cannot read property 'extract' of undefined

### ISSUE THREAD

**Issue by DiederikvandenB** [FullHuman/purgecss-webpack-plugin#48]
Hi,

Thank you for this package. Everything is working perfectly in development environment (without PurgeCSS). However, with [this configuration](https://gist.github.com/DiederikvandenB/588b8e01f5931a99757cfc761239cfe6), the plugin throws an error:

```
    at Purgecss.extractSelectors (/Users/Diederik/Sites/3_CUSTOMERS/5_ONBOARD/node_modules/purgecss/lib/purgecss.js:713:43)
    at Purgecss.extractFileSelector (/Users/Diederik/Sites/3_CUSTOMERS/5_ONBOARD/node_modules/purgecss/lib/purgecss.js:647:112)
    at Purgecss.purge (/Users/Diederik/Sites/3_CUSTOMERS/5_ONBOARD/node_modules/purgecss/lib/purgecss.js:409:41)
    at /Users/Diederik/Sites/3_CUSTOMERS/5_ONBOARD/node_modules/purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js:262:79
    at Array.forEach (<anonymous>)
    at /Users/Diederik/Sites/3_CUSTOMERS/5_ONBOARD/node_modules/purgecss-webpack-plugin/lib/purgecss-webpack-plugin.js:231:23
    at Array.forEach (<anonymous>)
   [...]
```

Whenever I remove [these lines](https://gist.github.com/DiederikvandenB/588b8e01f5931a99757cfc761239cfe6#file-webpack-prod-js-L28-L33), the build process succeeds, but too much CSS gets removed. Hence the implementation of the extractor class.

Any ideas?

**Comment by jsnanigans** [comment]
Hi, sorry for the late response.
could you check what the output of the glob.sync is at https://gist.github.com/DiederikvandenB/588b8e01f5931a99757cfc761239cfe6#file-webpack-prod-js-L24-L27 ?
